name: 'Run Flutter Checks'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Iterable/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.6'
          channel: 'stable'
      - run: flutter test

  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: Iterable/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: 'Create env file'
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo JWT_API_KEY=${{ secrets.JWT_API_KEY }} >> .env
          echo JWT_TOKEN=${{ secrets.JWT_TOKEN }} >> .env
          cat .env
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle

  build-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: Iterable/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: 'Create env file'
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo JWT_API_KEY=${{ secrets.JWT_API_KEY }} >> .env
          echo JWT_TOKEN=${{ secrets.JWT_TOKEN }} >> .env
          cat .env
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.6'
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --no-codesign

